### PR TITLE
feat: add tx signing instructions modal

### PR DESCRIPTION
**Pull request by paouvrard**
Add instruction modals telling the user to sign a tx with the Ethereum wallet or that he will be redirected to the NEAR wallet.
https://github.com/aurora-is-near/rainbow-bridge-frontend/issues/172
image
image
@corwinharrell Could you provide an icon for the NEAR redirect modal similar to the Ethereum one ? I couldn't find in the figma.

### CODE REVIEW

**Comment by corwinharrell** [comment]
@paouvrard my only concern with adding the NEAR variant is that the transition happens so quickly that the message gets flashed and redirects before the user gets a chance to read it. What is the timing like here and is it common to run into a scenario where there is a significant delay before the redirect occurs?

**Comment by paouvrard** [comment]
@corwinharrell There is a 3sec sleep to let the user read the message before the redirect.

**Comment by corwinharrell** [comment]
Ok, let's add a button here then incase they want to manually trigger the redirect. I've added another modal variant in Figma:

Screen Shot 2021-04-27 at 11 57 43 AM

**Comment by paouvrard** [comment]
Fixes: https://github.com/aurora-is-near/rainbow-bridge-frontend/issues/234, https://github.com/aurora-is-near/rainbow-bridge-frontend/issues/229
When the transfer is created: warn about transfer duration and gas cost estimation
image
image

When the transfer is finalized:
image
image


@djsatok @dafacto Could you please review the text ?

**Comment by dafacto** [comment]
Pierre, here's some suggested text tweaks (I'd use Gwei rather than gWei, even if the latter is correct. It looks weird, and I see Gwei used more often.)

Confirm Ethereum transaction:

Transfers are a two-step process, requiring confirmations in both your Ethereum and NEAR wallets.

After confirming with your Ethereum wallet, you’ll need to return about 10 minutes later to confirm with your NEAR wallet.

Once initiated from Ethereum, the transfer can not be canceled.

[Confirm transaction to proceed]


Confirm NEAR transaction:

Transfers are a two-step process, requiring confirmations in both your NEAR and Ethereum wallets.

After confirming with your NEAR wallet, you’ll need to return about 24 hours later to confirm with your Ethereum wallet. 

Note that when gas is expensive on Ethereum—say 100 Gwei—the transaction could cost around 0.05 ETH, and once initiated from NEAR, the transfer can not be canceled.

[Continue to NEAR wallet to confirm]

**Pull request merged**
